# Generated by Django 4.2.5 on 2023-11-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='news_pictures/')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('projects', 'Projects'), ('notices', 'Notices'), ('statements', 'Statements')], max_length=20)),
            ],
        ),
    ]
