# Generated by Django 4.2.5 on 2023-11-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_news_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='picture',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('statements', 'Statements'), ('notices', 'Notices'), ('projects', 'Projects')], max_length=20),
        ),
    ]
