# Generated by Django 4.2.5 on 2023-11-20 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
