# Generated by Django 4.2.5 on 2023-12-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_uploadedfile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('statements', 'Statements'), ('notices', 'Notices'), ('projects', 'Projects')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories_images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
