name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set PythonAnywhere API Token
        run: echo "PYTHONANYWHERE_API_TOKEN=${{ secrets.PYTHONANYWHERE_API_TOKEN }}" >> $GITHUB_ENV

      - name: Deploy to PythonAnywhere
        run: |
          pip install --upgrade pythonanywhere
          pa_autoconfigure_django.py --python=3.9 https://github.com/oweeengk/Kalimudan.git
