name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set PythonAnywhere API Token
        run: echo "PYTHONANYWHERE_API_TOKEN=${{ secrets.09e1356b6b2bb09ad0fb1fba22a0ad93598128e7 }}" >> $GITHUB_ENV

      - name: Deploy to PythonAnywhere
        run: |
          pip install --upgrade pythonanywhere
          pa_autoconfigure_django.py --python=3.8 https://github.com/your-username/your-repo.git
